class Profissoes{

  List<String> profissoes= [
    "Engenharia",
    "Medicina",
    "Biomedicina",
    "Direito",
    "Agronomia",
    "Ciências Econômicas",
    "Física",
    "Astronomia",
    "Matemática",
    "Ciencias da Computação",
    "Pedagogia",
    "Psicologia",
    "Geografia",
    "Medicina Veterinária",
    "Biotecnologia",
    "Zootecnia",
    "Arquitetura",
    "Estatística",
    "Geologia",
    "Administração",
    "Odontologia",
    "Inteligência Artificial",
    "Cartografia",
    "História",
    "Enfermagem",
    "Fisioterapia",
    "Marketing",
    "Farmácia",
    "Sistemas de informação",
    "Artes cênicas",
    "Design",
    "Jornalismo",
    "Moda",
    "Música",
    "Teologia",
    "Turismo",
    "Publicidade"
  ];

}